import { Pressable, ScrollView, Text, View } from 'react-native';
import { useState } from 'react';
import { router } from 'expo-router';
import { Banknote, Check, CreditCard, MapPin, WalletCards } from 'lucide-react-native';
import { ScreenHeader } from '@/components/ui/ScreenHeader';
import { AppButton } from '@/components/ui/AppButton';
import { useCartStore } from '@/stores/useCartStore';

const methods = [{ id: 'multicaixa', label: 'Referência Multicaixa', icon: WalletCards, hint: 'Paga após confirmares' }, { id: 'cash', label: 'Numerário na entrega', icon: Banknote, hint: 'Leva o valor exacto sempre que possível' }, { id: 'card', label: 'Cartão bancário', icon: CreditCard, hint: 'Brevemente disponível' }];
export default function PaymentScreen() { const [method, setMethod] = useState('multicaixa'); const lines = useCartStore((state) => state.lines); const total = lines.reduce((sum, line) => sum + line.price * line.quantity, 0) + 900; return <View className="flex-1 bg-surface px-5 dark:bg-slate-950"><ScreenHeader title="Finalizar pedido" subtitle="Confirma entrega e pagamento" /><ScrollView contentContainerClassName="pb-32"><View className="mb-6 rounded-2xl bg-white p-4 dark:bg-slate-900"><View className="flex-row items-center gap-3"><View className="rounded-xl bg-brand-soft p-3"><MapPin size={20} color="#FF5B26" /></View><View className="flex-1"><Text className="font-black text-ink dark:text-white">Casa</Text><Text className="mt-1 text-sm text-muted">Rua da Missão, Ingombota</Text></View><Text className="font-bold text-brand">Alterar</Text></View></View><Text className="mb-3 text-lg font-black text-ink dark:text-white">Como queres pagar?</Text>{methods.map(({ id, label, icon: Icon, hint }) => <Pressable key={id} onPress={() => id !== 'card' && setMethod(id)} className={`mb-3 flex-row items-center gap-3 rounded-2xl border p-4 ${method === id ? 'border-brand bg-brand-soft' : 'border-slate-100 bg-white dark:border-slate-800 dark:bg-slate-900'} ${id === 'card' ? 'opacity-50' : ''}`}><View className="rounded-xl bg-white p-2 dark:bg-slate-800"><Icon size={20} color="#FF5B26" /></View><View className="flex-1"><Text className="font-black text-ink dark:text-white">{label}</Text><Text className="mt-1 text-xs text-muted">{hint}</Text></View>{method === id ? <View className="h-6 w-6 items-center justify-center rounded-full bg-brand"><Check size={14} color="#FFFFFF" /></View> : null}</Pressable>)}<View className="mt-4 rounded-2xl bg-white p-4 dark:bg-slate-900"><Text className="text-sm text-muted">Total a pagar</Text><Text className="mt-1 text-2xl font-black text-ink dark:text-white">{total.toLocaleString('pt-PT')} Kz</Text></View></ScrollView><View className="absolute bottom-5 left-5 right-5"><AppButton label="Confirmar pedido" onPress={() => router.replace('/order/confirmed')} /></View></View>; }
