import type { ReactNode } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { CarFront, Check, Headphones, MapPin, Phone, Star } from 'lucide-react-native';
import { ScreenHeader } from '@/components/ui/ScreenHeader';
import { AppButton } from '@/components/ui/AppButton';
import { useOrderStore } from '@/stores/useOrderStore';

const steps = ['Pedido confirmado', 'Reboque a caminho', 'Chegada ao local', 'Serviço concluído'];
export default function OrderDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const order = useOrderStore((state) => state.orders.find((item) => item.id === id) ?? state.selectedOrder);
  const current = order.status === 'matching' ? 0 : order.status === 'on_the_way' ? 1 : 3;
  const active = order.status === 'on_the_way';
  return <View className="flex-1 bg-surface px-5 dark:bg-slate-950"><ScreenHeader title={active ? 'Acompanhar assistência' : 'Detalhes da assistência'} subtitle={`Pedido ${order.id}`} /><ScrollView contentContainerClassName="pb-10"><View className="mb-5 h-52 justify-end overflow-hidden rounded-[30px] bg-green-100 p-5"><View className="absolute -right-5 -top-8 h-32 w-32 rounded-full bg-green-200" /><View className="absolute bottom-16 left-12 h-2 w-56 rotate-[-20deg] rounded-full bg-white/70" /><View className="self-end rounded-2xl bg-brand p-4"><CarFront size={30} color="#FFFFFF" /></View><Text className="mt-3 text-xl font-black text-ink">{active ? `${order.provider} está a caminho` : 'Assistência concluída'}</Text><Text className="mt-1 text-sm text-slate-600">{active ? `Chegada estimada: ${order.etaMinutes} min` : `${order.category} · ${order.amount.toLocaleString('pt-PT')} Kz`}</Text></View><View className="mb-5 rounded-3xl bg-white p-5 dark:bg-slate-900"><Text className="mb-4 text-lg font-black text-ink dark:text-white">Estado da assistência</Text>{steps.map((step, index) => <View key={step} className="flex-row gap-3"><View className="items-center"><View className={`h-7 w-7 items-center justify-center rounded-full ${index <= current ? 'bg-brand' : 'bg-slate-200 dark:bg-slate-700'}`}>{index <= current ? <Check size={15} color="#FFFFFF" /> : null}</View>{index < steps.length - 1 ? <View className={`h-7 w-0.5 ${index < current ? 'bg-brand' : 'bg-slate-200 dark:bg-slate-700'}`} /> : null}</View><View className="pt-1"><Text className={`font-bold ${index <= current ? 'text-ink dark:text-white' : 'text-muted'}`}>{step}</Text>{index === current && active ? <Text className="mt-1 text-xs text-brand">Agora</Text> : null}</View></View>)}</View><View className="rounded-3xl bg-white p-5 dark:bg-slate-900"><View className="flex-row items-center gap-3"><View className="h-12 w-12 items-center justify-center rounded-2xl bg-brand"><Text className="font-black text-white">JM</Text></View><View className="flex-1"><Text className="font-black text-ink dark:text-white">{order.provider ?? 'Leva Já Assistência'}</Text><Text className="mt-1 text-sm text-muted">Condutor verificado · 4.9 ★</Text></View><Phone size={21} color="#16A34A" /></View><View className="my-4 h-px bg-slate-100 dark:bg-slate-800" /><Info icon={<CarFront size={20} color="#16A34A" />} text={order.vehicle} /><Info icon={<MapPin size={20} color="#16A34A" />} text={order.address} /></View><View className="mt-5 gap-3">{active ? <AppButton label="Preciso de ajuda" icon={<Headphones size={18} color="white" />} onPress={() => router.push('/support')} /> : null}<AppButton label="Avaliar assistência" variant="ghost" icon={<Star size={18} color="#16A34A" />} onPress={() => router.push('/order/rate')} /></View></ScrollView></View>;
}
function Info({ icon, text }: { icon: ReactNode; text: string }) { return <View className="mb-3 flex-row items-center gap-3">{icon}<Text className="flex-1 text-sm text-muted">{text}</Text></View>; }
