import { Pressable, ScrollView, Text, View } from 'react-native';
import { router as expoRouter } from 'expo-router';
import { useState } from 'react';
import { Banknote, ClipboardList, Star, ToggleLeft, ToggleRight, Truck } from 'lucide-react-native';
import { ProviderMetric } from '@/components/provider/ProviderMetric';
import { ProviderStatusPill } from '@/components/provider/ProviderStatusPill';
import { useOrderStore } from '@/stores/useOrderStore';
const router = { push: (path: string) => expoRouter.push(path as never) };
export default function ProviderHome() { const [online, setOnline] = useState(true); const order = useOrderStore((state) => state.selectedOrder); return <ScrollView className="flex-1 bg-surface dark:bg-slate-950" contentContainerClassName="px-5 pb-10 pt-16"><View className="flex-row items-start justify-between"><View><Text className="text-sm text-muted">Bom dia, João</Text><Text className="mt-1 text-3xl font-black text-ink dark:text-white">O teu painel</Text></View><Pressable onPress={() => setOnline(!online)} className={`flex-row items-center gap-2 rounded-2xl px-3 py-3 ${online ? 'bg-brand-soft' : 'bg-slate-200'}`}>{online ? <ToggleRight size={24} color="#16A34A" /> : <ToggleLeft size={24} color="#64748B" />}<Text className={`font-black ${online ? 'text-brand' : 'text-slate-600'}`}>{online ? 'Online' : 'Offline'}</Text></Pressable></View><View className="mt-7 flex-row gap-3"><ProviderMetric label="Ganhos hoje" value="42.500 Kz" icon={<Banknote size={19} color="#16A34A" />} /><ProviderMetric label="Avaliação" value="4,9" icon={<Star size={19} color="#16A34A" />} /><ProviderMetric label="Serviços" value="3" icon={<ClipboardList size={19} color="#16A34A" />} /></View><Text className="mb-3 mt-8 text-lg font-black text-ink dark:text-white">Pedido em curso</Text><Pressable onPress={() => router.push(`/provider/request/${order.id}`)} className="rounded-3xl bg-ink p-5"><View className="flex-row items-center justify-between"><ProviderStatusPill status={order.status} /><Truck size={28} color="#86EFAC" /></View><Text className="mt-4 text-xl font-black text-white">{order.category}</Text><Text className="mt-2 text-sm text-slate-300">{order.address} · {order.amount.toLocaleString('pt-PT')} Kz</Text><Text className="mt-4 font-bold text-green-200">Abrir serviço →</Text></Pressable><View className="mt-7 flex-row gap-3"><Quick label="Pedidos próximos" onPress={() => router.push('/provider/requests')} /><Quick label="Ganhos" onPress={() => router.push('/provider/earnings')} /><Quick label="Perfil" onPress={() => router.push('/provider/profile')} /></View></ScrollView>; }
function Quick({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable onPress={onPress} className="flex-1 rounded-2xl bg-white p-3 dark:bg-slate-900"><Text className="text-center text-xs font-black text-brand">{label}</Text></Pressable>; }
