import { Pressable, ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Minus, Plus, Trash2 } from 'lucide-react-native';
import { ScreenHeader } from '@/components/ui/ScreenHeader';
import { AppButton } from '@/components/ui/AppButton';
import { useCartStore } from '@/stores/useCartStore';

export default function CartScreen() {
  const { lines, add, remove } = useCartStore(); const subtotal = lines.reduce((total, line) => total + line.price * line.quantity, 0); const fee = lines.length ? 900 : 0;
  return <View className="flex-1 bg-surface px-5 dark:bg-slate-950"><ScreenHeader title="O teu carrinho" subtitle={lines.length ? `${lines.length} produto(s) seleccionado(s)` : 'Ainda não adicionaste produtos'} /><ScrollView contentContainerClassName="pb-36">{lines.map((line) => <View key={line.id} className="mb-3 rounded-2xl bg-white p-4 dark:bg-slate-900"><View className="flex-row justify-between gap-4"><View className="flex-1"><Text className="font-black text-ink dark:text-white">{line.name}</Text><Text className="mt-1 text-sm text-muted">{line.price.toLocaleString('pt-PT')} Kz cada</Text></View><Pressable onPress={() => remove(line.id)} className="h-9 w-9 items-center justify-center rounded-xl bg-red-50"><Trash2 size={17} color="#DC2626" /></Pressable></View><View className="mt-4 flex-row items-center justify-between"><View className="flex-row items-center gap-3 rounded-xl bg-slate-50 p-1 dark:bg-slate-800"><Pressable onPress={() => remove(line.id)} className="h-8 w-8 items-center justify-center rounded-lg bg-white dark:bg-slate-700"><Minus size={15} color="#17212B" /></Pressable><Text className="w-5 text-center font-black text-ink dark:text-white">{line.quantity}</Text><Pressable onPress={() => add(line)} className="h-8 w-8 items-center justify-center rounded-lg bg-brand"><Plus size={15} color="#FFFFFF" /></Pressable></View><Text className="font-black text-ink dark:text-white">{(line.price * line.quantity).toLocaleString('pt-PT')} Kz</Text></View></View>)}{!lines.length ? <View className="items-center rounded-3xl bg-white px-6 py-12 dark:bg-slate-900"><Text className="text-lg font-black text-ink dark:text-white">O carrinho está vazio</Text><Text className="mt-2 text-center text-sm text-muted">Explora os parceiros disponíveis e adiciona os teus favoritos.</Text></View> : <View className="mt-4 rounded-3xl bg-white p-5 dark:bg-slate-900"><Text className="text-lg font-black text-ink dark:text-white">Resumo</Text><Line label="Produtos" value={subtotal} /><Line label="Taxa de entrega" value={fee} /><View className="my-4 h-px bg-slate-100 dark:bg-slate-800" /><Line label="Total" value={subtotal + fee} bold /></View>}</ScrollView>{lines.length ? <View className="absolute bottom-5 left-5 right-5"><AppButton label="Continuar para pagamento" onPress={() => router.push('/checkout/payment')} /></View> : null}</View>;
}
function Line({ label, value, bold = false }: { label: string; value: number; bold?: boolean }) { return <View className="mt-4 flex-row justify-between"><Text className={bold ? 'font-black text-ink dark:text-white' : 'text-muted'}>{label}</Text><Text className={bold ? 'font-black text-ink dark:text-white' : 'font-semibold text-ink dark:text-white'}>{value.toLocaleString('pt-PT')} Kz</Text></View>; }
