import { Pressable, ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { DatabaseZap, LayoutDashboard, Smartphone, Truck } from 'lucide-react-native';
import { ScreenHeader } from '@/components/ui/ScreenHeader';
import { useOrderStore } from '@/stores/useOrderStore';
import { demoScenarios, presentationSeed } from '@/mocks/demo';

const targets: Record<string, string> = { tracking: '/order/LJ-2601', provider: '/provider/request/LJ-2604', arrival: '/provider/request/LJ-2603', 'payment-failed': '/request/payment-result', dispute: '/admin/detail/safety/SOS-40' };
export default function DemoCenter() { const loadScenario = useOrderStore((state) => state.loadScenario); return <View className="flex-1 bg-surface px-5 dark:bg-slate-950"><ScreenHeader title="Demo Center" subtitle="Cenários mockados para apresentação" /><ScrollView contentContainerClassName="pb-8"><View className="rounded-3xl bg-ink p-5"><DatabaseZap size={28} color="#86EFAC" /><Text className="mt-4 text-xl font-black text-white">Dados de demonstração prontos</Text><Text className="mt-2 text-sm leading-6 text-slate-300">Cada cenário reinicia o pedido, o pagamento, o prestador e o tracking. A alteração de estado feita pelo prestador reflecte-se imediatamente no cliente.</Text></View><Text className="mb-3 mt-6 text-lg font-black text-ink dark:text-white">Fluxos preparados</Text>{demoScenarios.map((scenario, index) => <Pressable key={scenario.id} onPress={() => { loadScenario(scenario); router.push(targets[scenario.id] as never); }} className="mb-3 rounded-3xl bg-white p-5 dark:bg-slate-900"><View className="flex-row items-center gap-3"><View className="h-11 w-11 items-center justify-center rounded-2xl bg-brand-soft">{index < 2 ? <Smartphone size={21} color="#16A34A" /> : index < 4 ? <Truck size={21} color="#16A34A" /> : <LayoutDashboard size={21} color="#16A34A" />}</View><View className="flex-1"><Text className="font-black text-ink dark:text-white">{scenario.title}</Text><Text className="mt-1 text-sm leading-5 text-muted">{scenario.description}</Text></View></View><Text className="mt-4 font-black text-brand">Carregar cenário →</Text></Pressable>)}<Text className="mb-3 mt-5 text-lg font-black text-ink dark:text-white">Seed disponível</Text><View className="rounded-3xl bg-white p-5 dark:bg-slate-900"><Text className="font-black text-ink dark:text-white">{presentationSeed.customer.name} · {presentationSeed.provider.name}</Text><Text className="mt-2 text-sm leading-6 text-muted">{presentationSeed.customer.vehicles.join(' · ')}{`\n`}{presentationSeed.workshops.join(' · ')}{`\n`}Zonas: {presentationSeed.zones.join(', ')}</Text></View></ScrollView></View>; }
