import type { ReactNode } from 'react';
import { ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { BadgeCheck, CarFront, Clock3, MapPin } from 'lucide-react-native';
import { AppButton } from '@/components/ui/AppButton';
import { ScreenHeader } from '@/components/ui/ScreenHeader';

export default function EstimateScreen() { return <View className="flex-1 bg-surface px-5 dark:bg-slate-950"><ScreenHeader title="Estimativa da assistência" subtitle="Passo 4 de 4" /><ScrollView contentContainerClassName="pb-28"><View className="rounded-[30px] bg-ink p-6"><View className="flex-row items-center gap-3"><View className="rounded-2xl bg-brand p-3"><CarFront size={24} color="#fff" /></View><View><Text className="text-sm font-bold text-green-200">REBOQUE DE VIATURA</Text><Text className="mt-1 text-xl font-black text-white">Toyota Corolla · 2015</Text></View></View><View className="my-5 h-px bg-white/10" /><View className="flex-row items-center gap-2"><MapPin size={17} color="#86EFAC" /><Text className="text-sm text-slate-300">Rua da Missão, Ingombota</Text></View></View><View className="mt-5 rounded-3xl bg-white p-5 dark:bg-slate-900"><View className="flex-row items-end justify-between"><View><Text className="text-sm text-muted">Preço estimado</Text><Text className="mt-2 text-3xl font-black text-ink dark:text-white">18.500 Kz</Text></View><View className="rounded-xl bg-brand-soft px-3 py-2"><Text className="text-xs font-black text-brand">PREÇO BASE</Text></View></View><View className="my-5 h-px bg-slate-100 dark:bg-slate-800" /><Info icon={<Clock3 size={18} color="#16A34A" />} text="Chegada estimada em 18–25 min" /><Info icon={<BadgeCheck size={18} color="#16A34A" />} text="O valor final é confirmado antes do serviço" /></View><Text className="mt-5 text-center text-xs leading-5 text-muted">Ao confirmar, procuraremos um prestador disponível próximo de ti.</Text></ScrollView><View className="absolute bottom-0 left-0 right-0 border-t border-slate-100 bg-surface px-5 pb-7 pt-4 dark:border-slate-800 dark:bg-slate-950"><AppButton label="Confirmar pedido" onPress={() => router.push('/request/matching')} /></View></View>; }
function Info({ icon, text }: { icon: ReactNode; text: string }) { return <View className="mb-3 flex-row items-center gap-3"><View className="h-9 w-9 items-center justify-center rounded-xl bg-brand-soft">{icon}</View><Text className="flex-1 text-sm text-muted">{text}</Text></View>; }
