import { useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Car, CarFront, Truck } from 'lucide-react-native';
import { AppButton } from '@/components/ui/AppButton';
import { ScreenHeader } from '@/components/ui/ScreenHeader';

const vehicles = [{ label: 'Toyota Corolla', detail: '2015 · LD-42-18-AF', icon: Car }, { label: 'Kia Sportage', detail: '2018 · LD-10-96-CC', icon: CarFront }, { label: 'Outra viatura', detail: 'Adicionar dados manualmente', icon: Truck }];
export default function VehicleScreen() { const [selected, setSelected] = useState(0); return <View className="flex-1 bg-surface px-5 dark:bg-slate-950"><ScreenHeader title="Qual é a viatura?" subtitle="Passo 2 de 4" /><ScrollView contentContainerClassName="pb-28"><Text className="mb-6 text-base leading-6 text-muted">A informação ajuda o reboque a chegar preparado.</Text><View className="gap-3">{vehicles.map(({ label, detail, icon: Icon }, index) => { const active = selected === index; return <Pressable key={label} onPress={() => setSelected(index)} className={`flex-row items-center gap-4 rounded-3xl border p-5 ${active ? 'border-brand bg-brand-soft' : 'border-transparent bg-white dark:bg-slate-900'}`}><View className={`h-12 w-12 items-center justify-center rounded-2xl ${active ? 'bg-brand' : 'bg-slate-100 dark:bg-slate-800'}`}><Icon size={24} color={active ? '#fff' : '#16A34A'} /></View><View className="flex-1"><Text className="font-black text-ink dark:text-white">{label}</Text><Text className="mt-1 text-sm text-muted">{detail}</Text></View><View className={`h-5 w-5 rounded-full border-2 ${active ? 'border-brand bg-brand' : 'border-slate-300'}`} /></Pressable>; })}</View><View className="mt-7 rounded-3xl bg-white p-5 dark:bg-slate-900"><Text className="font-black text-ink dark:text-white">Dica de segurança</Text><Text className="mt-2 text-sm leading-6 text-muted">Se estiveres numa via movimentada, liga os quatro piscas e mantém-te num local seguro.</Text></View></ScrollView><View className="absolute bottom-0 left-0 right-0 border-t border-slate-100 bg-surface px-5 pb-7 pt-4 dark:border-slate-800 dark:bg-slate-950"><AppButton label="Confirmar viatura" onPress={() => router.push('/request/location')} /></View></View>; }
